---
name: "YoutubeSync"
guid: "17438c58-4f70-4628-8759-8fc3fbcf0552"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Automactlly sync youtube videos into your local videos"
description: >
  Automactlly sync youtube videos into your videos
  Enjoyyy.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.YoutubeSync.dll"
changelog: >
  changelog
